apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metric-server
  namespace: <NAMESPACE-NAME>
  labels:
    app: metric-server
spec:
  interval: 1m0s
  path: ./<PATH-TO-THIS-FILE-ON-REPO>/spec
  prune: true
  sourceRef:
    kind: GitRepository
    name: <GITREPOSITORY-SOURCE-NAME>
    namespace: flux-system
